name: 'CI: build and publish'

on:
  push:
    branches:
      - test
      - prod
jobs:
  build_and_push_image:
    uses: hkaibara/CI-Workflows/.github/workflows/publish-python.yml@main
    with:
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      GH_PAT: ${{ secrets.GH_PAT }}
      