name: 'Versioning'
on:
  pull_request:
    types: 
     - closed

permissions:
  id-token: write
  contents: write

jobs:
  Tag:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'test'
    uses: hkaibara/CI-Workflows/.github/workflows/versioning.yml@main
    with:
      runner: ubuntu-latest
      checkout_ref: ${{github.event.pull_request.merge_commit_sha}}
      bump: |-
        ${{
             contains(github.event.pull_request.labels.*.name, 'Major')  && 'major'
          || contains(github.event.pull_request.labels.*.name, 'Minor')  && 'minor'
          || contains(github.event.pull_request.labels.*.name, 'Hotfix') && 'patch'
          || contains(github.event.pull_request.labels.*.name, 'Patch')  && 'patch'
          || 'none'
        }}

  Release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'prod'
    uses: hkaibara/CI-Workflows/.github/workflows/release.yml@main
    with:
      runner: ubuntu-latest
      checkout_ref: ${{github.event.pull_request.merge_commit_sha}}
  
  Verbose1:
    runs-on: ubuntu-latest
    needs: Tag
    steps:
      - name: Outputs
        run: |
          echo ${{needs.Tag.outputs.tag}}

  Verbose2:
    runs-on: ubuntu-latest
    needs: Release
    steps:
      - name: Outputs
        run: |
          echo ${{needs.Release.outputs.tag}}