name: 'CI'

on:
  push:
    branches: [dockerhub]

permissions:
      id-token: write
      contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{secrets.AWS_ROLE}}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{vars.AWS_REGION}}

    - name: Check Credentials
      run: |
       aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: public.ecr.aws/a2e5a4o5/app-test-public
        ECR_REPOSITORY: app-test-public
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws ecr get-login-password --region ap-northeast-1
        docker login --username AWS --password-stdin 214084917052.dkr.ecr.ap-northeast-1.amazonaws.com
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
    #   with:
    #     images: ${{secrets.DOCKER_CR}}
    #     tags: |

    #     type=sha  

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: "{{defaultContext}}"
    #     push: true
    #     tags: ${{ steps.meta.outputs.defaultContext.sha}}
    #     labels: ${{ steps.meta.outputs.labels }}


    - name: Download Kustomize
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -o $GITHUB_WORKSPACE/bin/kustomize_v5.4.1_linux_amd64.tar.gz --location "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.1/kustomize_v5.4.1_linux_amd64.tar.gz"
        tar -xvzf $GITHUB_WORKSPACE/bin/kustomize_v5.4.1_linux_amd64.tar.gz
        chmod u+x $GITHUB_WORKSPACE/kustomize

    - name: Check out manifest
      uses: actions/checkout@v3
      with:
        repository: hkaibara/deployment-repo
        ref: main
        token: ${{ secrets.GH_PAT }}
        
    - name: Update Manifest Image Tag
      run: |
        ls -l
        cd app1/env/test
        kustomize edit set image app-test=public.ecr.aws/a2e5a4o5/app-test-public:${{ github.sha }}
        git config user.name hkaibara
        git config user.email hiroshi.kaibara.hk@gmail.com
        git add .
        git diff-index --quiet HEAD || git commit --message "Update Image"
        git push