name: "tagged-release"

on:
  push:
    branches:
      - prod

permissions:
  id-token: write
  contents: write

jobs:
  Bump_version:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
  
      - name: release tag
        id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false


      - name: verbose
        run: |
          echo ${{steps.release.outputs.automatic_releases_tag}}

