name: 'release'
on:
  push:
    branches:
      - test
      - prod

permissions:
  id-token: write
  contents: write

jobs:
  Bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
  
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: |-
            ${{
                 github.event.label.name == 'Major' && 'major'
              || github.event.label.name == 'Minor' && 'minor'
              || github.event.label.name == 'hotfix' && 'minor'
              ||                                        'patch'
            }}