name: 'release'
on:
  push:
    branches:
      - prod

permissions:
  id-token: write
  contents: write

jobs:
  Bump_version:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
  
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: prod
          DEFAULT_BRANCH: prod
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: none
