name: 'release'
on:
  pull_request:
    types: 
     - closed

permissions:
  id-token: write
  contents: write

jobs:
  Bump_version:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ github.event.pull_request.base.sha }}
  
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: prod
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: |-
            ${{
                 github.event.pull_request.labels.name == 'Major' && 'major'
              || github.event.pull_request.labels.name == 'Minor' && 'minor'
              || github.event.pull_request.labels.name == 'Hotfix' && 'patch'
              || github.event.pull_request.labels.name == 'Patch' && 'patch'
              || 'none'
            }}

      - name: verbose
        run: |
          echo ${{steps.bump.outputs.new_tag}}
          echo ${{steps.bump.outputs.tag}}
          echo ${{steps.bump.outputs.part}}
          echo ${{steps.bump.outputs.old_tag}}
          echo ${{github.event.pull_request.labels.*.name}}
          
      - name: github context
        env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"