name: 'release'
on:
  push:
    tags: 
      - 1*
      - 2*
      - 3*

permissions:
  id-token: write
  contents: read

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        uses: actions/checkout@v3
      - name: Tag commit
        run: 
          pwd
          ls -al