name: 'Versioning'
on:
  workflow_call:
      inputs:
        bump:
          type: string
          required: true
      secrets:
        GITHUB_TOKEN:
          required: true

jobs:
  Versioning:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
  
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: prod
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: ${{inputs.bump}}

  Release_Version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'prod'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
  
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: prod
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: ${{inputs.bump}}

      - name: release tag
        id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{steps.bump.outputs.tag}}"